#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Sensor, dgtl2,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  ,               sensorTouch)
#pragma config(Sensor, dgtl5,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  TouchSensor_Updown, sensorTouch)
#pragma config(Sensor, dgtl10, Test,           sensorDigitalIn)
#pragma config(Motor,  port1,           LeftRun_1,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LeftRun_2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Intake_1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Claw_1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightRun_1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RightRun_2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Shoot_1,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#warning "this file for Macro Definition about task_name and global variable"
#include"unknow.h"   	//some of data base element from bottom
#include"library.h"		//same as void.h ,provide all function elements
#include"Remove.h"		//same as joystick.h this file call the function element from system or library.h
#include"auto.h"			//this file for auto program ,use it try to program auto program
//!!!***do not change the path of those folder,and do not change library functions,these operation are so dangerous****!!!//
task main(){
	while(1){
		clearTimer(T1);
		while(time1[T1] < 10){
			choose();
		}
		if(auto_1 == 1){
			clearTimer(T3);
			if(time1[T3] <= 15000){
				auto();
				remove_1 = 1;
			}
			else{
				remove_1 = 1;
			}
		}
		if(remove_1 == 1){
			remove();
		}
	}
}
